version: 2.1
orbs:
  release-tag: kobtea/release-tag@0.0.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/kobtea/sample-circleci

jobs:
  lint:
    docker:
      - image: golangci/golangci-lint
    working_directory: /go/src/github.com/kobtea/sample-circleci
    steps:
      - checkout
      - run: golangci-lint run -E golint,gofmt,goimports
  build:
    executor: golang
    steps:
      - checkout
      - run: make test
      - run: make build
  release:
    executor: golang
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          sudo apt-get update
          sudo apt-get install -y rpm
          echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USER --password-stdin
          curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  check:
    jobs:
      - lint
      - build
      - release-tag/tagging:
          fingerprint: bc:64:46:46:3c:c4:a2:2c:e2:1a:af:ae:07:c0:b1:39
          requires:
            - lint
            - build
  release:
    jobs:
      - release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
