version: 2.1
executors:
  golang:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/kobtea/sample-circleci

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run: make test
      - run: make build
