version: 2.1
orbs:
  release-tag: kobtea/release-tag@dev:master

executors:
  golang:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/kobtea/sample-circleci

jobs:
  lint:
    docker:
      - image: golangci/golangci-lint
    working_directory: /go/src/github.com/kobtea/sample-circleci
    steps:
      - checkout
      - run: golangci-lint run -E golint,gofmt,goimports
  build:
    executor: golang
    steps:
      - checkout
      - run: make test
      - run: make build

workflows:
  version: 2
  check:
    jobs:
      - lint
      - build
      - release-tag/tagging:
          fingerprint: bc:64:46:46:3c:c4:a2:2c:e2:1a:af:ae:07:c0:b1:39
